#!/usr/bin/env python3
"""Send a deduped Discord alert for hermes-webui-stack upgrade failures.

Designed for systemd OnFailure from hermes-webui-stack-autonomous-upgrade.service.
Reads the latest stack_upgrade_v2 JSON report, extracts the actionable blocker,
and posts to the infrastructure Discord channel using the profile bot token.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

STACK = Path('/home/jmelchiori/docker-compose/hermes-webui-stack')
STATE = STACK / 'state' / 'upgrade-v2'
DEFAULT_REPORT = STATE / 'last-autonomous-upgrade.json'
SECRET_CANDIDATES = [
    STACK / 'workspace/.secrets/discord.yaml',
    STACK / 'hermes-home/workspace/.secrets/discord.yaml',
]
DEDUP_PATH = STATE / 'alerts' / 'last-discord-alert.json'
PROFILE = 'infrastructure'
DISCORD_API_BASE = 'https://discord.com/api/v10'


def load_report(path: Path) -> dict[str, Any]:
    with path.open() as f:
        return json.load(f)


def load_discord_secret(profile: str = PROFILE) -> tuple[str, str]:
    """Return (bot_token, channel_id) from the simple profile YAML secret file.

    Avoid PyYAML dependency because this runs from host systemd.
    """
    for path in SECRET_CANDIDATES:
        if not path.exists():
            continue
        current = None
        values: dict[str, str] = {}
        for raw in path.read_text().splitlines():
            line = raw.rstrip('\n')
            if not line.strip() or line.lstrip().startswith('#'):
                continue
            if not line.startswith((' ', '\t')) and line.endswith(':'):
                current = line[:-1].strip()
                continue
            if current == profile and ':' in line:
                key, value = line.strip().split(':', 1)
                values[key.strip()] = value.strip().strip('"\'')
        token = values.get('discord_bot_token', '')
        channel = values.get('discord_channel_id', '')
        if token and channel:
            return token, channel
    raise RuntimeError(f'No Discord bot token/channel found for profile {profile}')


def flatten_errors(report: dict[str, Any]) -> list[dict[str, Any]]:
    errors: list[dict[str, Any]] = []
    for err in report.get('errors') or []:
        if isinstance(err, dict):
            errors.append(err)
            for nested in err.get('backup_errors') or err.get('candidate_errors') or []:
                if isinstance(nested, dict):
                    errors.append(nested)
    return errors


def summarize(report: dict[str, Any], report_path: Path) -> tuple[str, str, str]:
    status = report.get('status', 'unknown')
    stage = report.get('stage', 'unknown')
    ts = report.get('timestamp_utc', '')
    errors = flatten_errors(report)
    codes = [str(e.get('code', 'unknown')) for e in errors] or ['unknown']
    title = f'Hermes stack update failed: {status}'

    lines = [
        f'**Hermes stack update failed**',
        f'- status: `{status}`',
        f'- stage: `{stage}`',
        f'- timestamp: `{ts or "unknown"}`',
        f'- report: `{report_path}`',
    ]

    candidate = report.get('candidate_manifest') or {}
    if candidate.get('candidate_id'):
        lines.append(f'- candidate: `{candidate.get("candidate_id")}`')

    for err in errors[:6]:
        code = err.get('code', 'unknown')
        msg = err.get('message', '')
        extras = []
        if 'root_free_gib' in err:
            extras.append(f"root_free={err.get('root_free_gib')}GiB")
        if 'min_root_free_gib' in err:
            extras.append(f"min={err.get('min_root_free_gib')}GiB")
        if 'workspace_head' in err:
            extras.append(f"workspace={str(err.get('workspace_head'))[:12]}")
        if 'build_head' in err:
            extras.append(f"build={str(err.get('build_head'))[:12]}")
        suffix = f" ({', '.join(extras)})" if extras else ''
        lines.append(f'- blocker `{code}`: {msg}{suffix}')

    if len(errors) > 6:
        lines.append(f'- plus {len(errors)-6} more errors in report')

    lines.append('')
    lines.append('This alert is generated by `hermes-webui-stack-upgrade-alert.service` via systemd `OnFailure=`.')
    content = '\n'.join(lines)
    # Dedupe by failure shape, not run timestamp. Repeated daily failures with
    # the same blocker should not spam Discord; a new candidate, status, stage,
    # code, or source/storage detail should alert again.
    blocker_fingerprint = []
    for err in errors:
        blocker_fingerprint.append({
            'code': err.get('code', 'unknown'),
            'workspace_head': err.get('workspace_head'),
            'build_head': err.get('build_head'),
            'root_free_gib': err.get('root_free_gib'),
            'min_root_free_gib': err.get('min_root_free_gib'),
        })
    fingerprint_src = json.dumps({
        'status': status,
        'stage': stage,
        'candidate': candidate.get('candidate_id'),
        'blockers': blocker_fingerprint,
    }, sort_keys=True)
    fingerprint = hashlib.sha256(fingerprint_src.encode()).hexdigest()[:16]
    return title, content[:1900], fingerprint


def should_send(fp: str, force: bool) -> bool:
    if force:
        return True
    try:
        state = json.loads(DEDUP_PATH.read_text())
    except Exception:
        return True
    return state.get('fingerprint') != fp


def mark_sent(fp: str, report_path: Path, status: str) -> None:
    DEDUP_PATH.parent.mkdir(parents=True, exist_ok=True)
    tmp = DEDUP_PATH.with_suffix('.tmp')
    tmp.write_text(json.dumps({
        'fingerprint': fp,
        'report': str(report_path),
        'status': status,
        'sent_at': time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()),
    }, indent=2, sort_keys=True) + '\n')
    tmp.replace(DEDUP_PATH)


def send_discord(token: str, channel: str, content: str) -> tuple[int, str]:
    url = f'{DISCORD_API_BASE}/channels/{channel}/messages'
    data = json.dumps({'content': content, 'allowed_mentions': {'parse': []}}).encode()
    req = urllib.request.Request(
        url,
        data=data,
        method='POST',
        headers={
            'Authorization': f'Bot {token}',
            'Content-Type': 'application/json',
            'User-Agent': 'hermes-stack-upgrade-alert/1.0',
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=20) as resp:
            body = resp.read().decode('utf-8', 'replace')
            return resp.status, body[:500]
    except urllib.error.HTTPError as exc:
        body = exc.read().decode('utf-8', 'replace')
        return exc.code, body[:1000]


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--report', default=str(DEFAULT_REPORT))
    ap.add_argument('--force', action='store_true')
    ap.add_argument('--dry-run', action='store_true')
    args = ap.parse_args(argv)

    report_path = Path(args.report)
    report = load_report(report_path)
    status = report.get('status')
    if status == 'ok' and not args.force:
        print(f'no alert: status ok in {report_path}')
        return 0

    title, content, fp = summarize(report, report_path)
    if not should_send(fp, args.force):
        print(f'no alert: duplicate fingerprint {fp}')
        return 0

    if args.dry_run:
        print(f'DRY RUN fingerprint={fp}')
        print(content)
        return 0

    token, channel = load_discord_secret(PROFILE)
    code, body = send_discord(token, channel, content)
    if 200 <= code < 300:
        mark_sent(fp, report_path, str(status))
        print(f'sent Discord alert to channel {channel}, fingerprint={fp}, http={code}')
        return 0
    print(f'ERROR: Discord send failed http={code}: {body}', file=sys.stderr)
    return 1


if __name__ == '__main__':
    raise SystemExit(main())
